ibtikar_glance_dashboard_room_news_list_new_recipe:
    path:  /list-new-recipe
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:listNewRecipe }



ibtikar_glance_dashboard_room_news_view_recipe:
    path:  /view/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:view }

ibtikar_glance_dashboard_room_news_edit:
    path:  /edit/{recipeId}
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:edit }

ibtikar_glance_dashboard_room_news_publish:
    path:  /publish
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:publish }


ibtikar_glance_dashboard_room_news_bulk_actions:
    path:  /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:bulk }

ibtikar_glance_dashboard_room_news_delete:
    path:  /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:delete }

ibtikar_glance_dashboard_room_news_list_assigned_recipe:
    path:  /list-assigned-recipe
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:listAssignedRecipe }


ibtikar_glance_dashboard_room_news_list_new_recipe_change_list_columns:
    path:  /new-recipe-change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:changeListNewRecipeColumns }

ibtikar_glance_dashboard_room_news_list_assigned_recipe_change_list_columns:
    path:  /assigned-recipe-change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:changeListAssignedRecipeColumns }

ibtikar_glance_dashboard_room_news_assign:
    path:  /assign
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:assign }

ibtikar_glance_dashboard_room_news_assign_to_me:
    path:  /assign-to-me
    defaults: { _controller: IbtikarGlanceDashboardBundle:rooms\News:assignToMe }



