ibtikar_glance_dashboard_job_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:create }

ibtikar_glance_dashboard_job_edit:
    path:  /edit/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:edit}

ibtikar_glance_dashboard_job_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:list }

ibtikar_glance_dashboard_job_delete:
    path: /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:delete}

ibtikar_glance_dashboard_job_bulk_actions:
    path: /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:bulk}

ibtikar_glance_dashboard_job_check_field_unique:
    path: /checkfieldUnique
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:checkFieldUnique }

ibtikar_glance_dashboard_job_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Job:changeListColumns }