ibtikar_glance_dashboard_magazine_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:create }

ibtikar_glance_dashboard_magazine_edit:
    path:  /edit/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:edit}

ibtikar_glance_dashboard_magazine_editPage:
    path:  /editPage/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:editMagazinePage}

ibtikar_glance_dashboard_magazine_delete:
    path:  /delete/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:delete }

ibtikar_glance_dashboard_magazine_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:list }

ibtikar_glance_dashboard_magazine_publish:
    path:  /ajax/publish
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:publish }

ibtikar_glance_dashboard_magazine_delete:
    path: /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:delete}

ibtikar_glance_dashboard_magazine_bulk_actions:
    path: /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:bulk}

ibtikar_glance_dashboard_magazine_check_field_unique:
    path: /checkfieldUnique
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:checkFieldUnique }

ibtikar_glance_dashboard_magazine_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Magazine:changeListColumns }