ibtikar_glance_dashboard_media_upload:
    path:  /upload/{type}/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:upload ,documentId: ~, collectionType: ~ }
    requirements:
        type:  file|image

ibtikar_glance_dashboard_media_crop:
    path:  /crop
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:crop }

material_upload_imageUrl:
    path:  /upload_imageUrl
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:upload_imageUrl }
ibtikar_glance_dashboard_media_bulk_actions:
    path: /{type}/bulk/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:bulk ,documentId: ~, collectionType: ~ }
    requirements:
        type:  file|image

ibtikar_glance_dashboard_media_user_files:
    path:  /user-files/{type}/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:userFiles ,documentId: ~, collectionType: ~ }
    requirements:
        type:  file|image

ibtikar_glance_dashboard_media_delete:
    path:  /delete/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:deleteFile }

google_upload_image:
    path:  /upload-image-from-google/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:uploadImageFromGoogle ,documentId: ~, collectionType: ~ }

