ibtikar_glance_dashboard_media_upload:
    path:  /upload/{type}/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:upload ,documentId: ~, collectionType: ~ }
    requirements:
        type:  file|image

ibtikar_glance_dashboard_media_crop:
    path:  /crop/{id}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:crop }

ibtikar_glance_dashboard_media_delete:
    path:  /delete/{id}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:deleteFile }


ibtikar_glance_dashboard_video_delete:
    path:  /delete/{id}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:deleteVideo }

ibtikar_glance_dashboard_media_user_files:
    path:  /user-files/{type}/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:userFiles ,documentId: ~, collectionType: ~ }
    requirements:
        type:  file|image|all

ibtikar_glance_dashboard_media_get_external:
    path:  /image-proxy
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:imageProxy }

recipe_upload_imageUrl:
    path:  /upload_imageUrl
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:upload_imageUrl }

#ibtikar_glance_dashboard_media_bulk_actions:
#    path: /{type}/bulk/{documentId}/{collectionType}
#    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:bulk ,documentId: ~, collectionType: ~ }
#    requirements:
#        type:  file|image
#
#
google_upload_image:
    path:  /upload-image-from-google/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:uploadImageFromGoogle ,documentId: ~, collectionType: ~ }



ibtikar_glance_dashboard_media_youtube_upload_video:
    path:  /upload-video-from-youtube/{type}/{documentId}/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:uploadYoutubeVideo , type: ~,documentId : ~,collectionType: ~}

youtube_validate_videoUrl:
    path:  /validate_videoUrl
    defaults: { _controller: IbtikarGlanceDashboardBundle:Media:validateYoutubeVideoUrl }