ibtikar_glance_dashboard_product_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:create }

ibtikar_glance_dashboard_product_edit:
    path:  /edit/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:edit}

ibtikar_glance_dashboard_product_delete:
    path:  /delete/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:delete }

ibtikar_glance_dashboard_product_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:list }

ibtikar_glance_dashboard_product_view:
    path: /view
    defaults: { _controller: IbtikarGlanceDashboardBundle:SubProduct:list }

ibtikar_glance_dashboard_product_delete:
    path: /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:delete}

ibtikar_glance_dashboard_product_bulk_actions:
    path: /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:bulk}

ibtikar_glance_dashboard_product_check_field_unique:
    path: /checkfieldUnique
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:checkFieldUnique }

ibtikar_glance_dashboard_product_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Product:changeListColumns }