ibtikar_glance_dashboard_role_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:create }

ibtikar_glance_dashboard_role_edit:
    path:  /edit/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:edit }

module_role_create:
    path:  /module-role-create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:edit }

ibtikar_glance_dashboard_role_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:list }

ibtikar_glance_dashboard_role_delete:
    path: /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:delete }

ibtikar_glance_dashboard_role_bulk_actions:
    path: /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:bulk}

ibtikar_glance_dashboard_role_check_field_unique:
    path: /checkfieldUnique
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:checkFieldUnique }

ibtikar_glance_dashboard_role_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:changeListColumns }

ibtikar_glance_dashboard_role_permissions_show:
    path:  /role-permissions-show
    defaults: { _controller: IbtikarGlanceDashboardBundle:Role:showRolePermission }