ibtikar_glance_dashboard_home:
    path:     /
    defaults: { _controller: IbtikarGlanceDashboardBundle:base\Backend:home }


ibtikar_glance_dashboard_not_found:
    path:  /not-found
    defaults: { _controller: IbtikarGlanceDashboardBundle:base\Backend:backendNotFound }

ibtikar_glance_redirect_create:
    path:  /redirect
    defaults: { _controller: IbtikarGlanceDashboardBundle:Redirect:create }

ibtikar_glance_redirect_batch:
    path:  /redirect/batch
    defaults: { _controller: IbtikarGlanceDashboardBundle:Redirect:batchInsert }

ibtikar_glance_redirect_edit:
    path:  /redirect/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Redirect:edit }

ibtikar_glance_dashboard_product:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/product.yml"
    prefix:   /product

ibtikar_glance_dashboard_banner:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/homebanner.yml"
    prefix:   /bannar

ibtikar_glance_dashboard_subproduct:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/subproduct.yml"
    prefix:   /subproduct

ibtikar_glance_dashboard_activity:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/activity.yml"
    prefix:   /activity

ibtikar_glance_dashboard_magazine:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/magazine.yml"
    prefix:   /magazine

ibtikar_glance_dashboard_tag:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/tag.yml"
    prefix:   /tag

ibtikar_glance_dashboard_recipesubcategory:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/recipesubcategory.yml"
    prefix:   /recipesubcategory

ibtikar_glance_dashboard_category:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/category.yml"
    prefix:   /category

ibtikar_glance_dashboard_media:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/media.yml"
    prefix:   /

ibtikar_glance_dashboard_page:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/page.yml"
    prefix:   /

ibtikar_glance_dashboard_competition:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/competition.yml"
    prefix:   /competition

ibtikar_glance_dashboard_recipe:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe.yml"
    prefix:   /recipe

ibtikar_glance_dashboard_recipe_news:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe/new.yml"
    prefix:   /recipe-new

ibtikar_glance_dashboard_recipe_draft:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe/draft.yml"
    prefix:   /recipe-draft

ibtikar_glance_dashboard_recipe_deleted:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe/deleted.yml"
    prefix:   /recipe-deleted

ibtikar_glance_dashboard_recipe_publish:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe/publish.yml"
    prefix:   /recipe-publish

ibtikar_glance_dashboard_recipe_autopublish:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe/autopublish.yml"
    prefix:   /recipe-autopublish

ibtikar_glance_dashboard_blog:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/blog.yml"
    prefix:   /blog

ibtikar_glance_dashboard_season:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/season.yml"
    prefix:   /season

ibtikar_glance_dashboard_stars:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/stars.yml"
    prefix:   /stars

ibtikar_glance_dashboard_causepage:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/causepage.yml"
    prefix:   /causepage

ibtikar_glance_dashboard_message:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/message.yml"
    prefix:   /message
