ibtikar_glance_dashboard_home:
    path:     /
    defaults: { _controller: IbtikarGlanceDashboardBundle:base\Backend:home }


ibtikar_glance_dashboard_not_found:
    path:  /not-found
    defaults: { _controller: IbtikarGlanceDashboardBundle:base\Backend:backendNotFound }


ibtikar_glance_dashboard_product:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/product.yml"
    prefix:   /product

ibtikar_glance_dashboard_subproduct:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/subproduct.yml"
    prefix:   /subproduct

ibtikar_glance_dashboard_category:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/category.yml"
    prefix:   /category

ibtikar_glance_dashboard_media:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/media.yml"
    prefix:   /

ibtikar_glance_dashboard_recipe:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/recipe.yml"
    prefix:   /recipe


ibtikar_glance_dashboard_recipe_news:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/rooms/news.yml"
    prefix:   /news-room



