parameters:
    per_page_items: 50
    autoCompelet_display_item: 5

services:
#    ibtikar_glance_dashboard.example:
#        class: Ibtikar\GlanceDashboardBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    list_view:
        class: Ibtikar\GlanceDashboardBundle\Service\ListView
        arguments: ["@service_container" ]

    base_email:
        class: Ibtikar\GlanceDashboardBundle\Service\BaseEmail
        arguments: ["@templating"]

    not_found_listener:
        class: Ibtikar\GlanceDashboardBundle\Service\NotFoundExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
        arguments: [ "@templating" ]

    update_actions_users:
        class: Ibtikar\GlanceDashboardBundle\Service\UpdateActionsUsers
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
        arguments: ["@service_container"]
        
    no_cache_respose_list:
     class: Ibtikar\GlanceDashboardBundle\Service\RemoveListCache
     tags:
         - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }     
