parameters:
    per_page_items: 10
    autoCompelet_display_item: 5
    router.request_context.host: %site_domain%

services:

    GlanceDashboardBundle.eventListeners.localeRewriteListener::
        class: Ibtikar\GlanceDashboardBundle\Listener\LanguageChangeListener
        arguments: ["@router", "%locale%", "%accepted_locales%"]
        tags:
              - { name: kernel.event_subscriber }

    GlanceDashboardBundle.eventListeners.SessionLanguageListener::
        class: Ibtikar\GlanceDashboardBundle\Listener\SessionLanguageListener
        arguments: ["@service_container","@router", "%locale%", "%accepted_locales%"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -255 }

    list_view:
        class: Ibtikar\GlanceDashboardBundle\Service\ListView
        arguments: ["@service_container" ]

    base_email:
        class: Ibtikar\GlanceDashboardBundle\Service\BaseEmail
        arguments: ["@templating"]

    frontend_base_email:
        class: Ibtikar\GlanceDashboardBundle\Service\FrontendBaseEmail
        arguments: ["@templating"]

    not_found_listener:
        class: Ibtikar\GlanceDashboardBundle\Service\NotFoundExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
        arguments: [ "@templating" ]

    recipe_operations:
        class: Ibtikar\GlanceDashboardBundle\Service\RecipeOperations
        arguments: [ "@service_container" ]

    document_operations:
        class: Ibtikar\GlanceDashboardBundle\Service\DocumentPublishOperations
        arguments: [ "@service_container" ]

    update_actions_users:
        class: Ibtikar\GlanceDashboardBundle\Service\UpdateActionsUsers
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
        arguments: ["@service_container"]

    no_cache_respose_list:
     class: Ibtikar\GlanceDashboardBundle\Service\RemoveListCache
     tags:
         - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    ajax_listener:
        class: Ibtikar\GlanceDashboardBundle\Listener\AjaxAuthenticationListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 255 }
        arguments: ["@router","@session","@translator"]
    publish_operations:
        class: Ibtikar\GlanceDashboardBundle\Service\PublishOperations
        arguments: [ "@doctrine_mongodb" ]

    redirect:
        class: Ibtikar\GlanceDashboardBundle\Service\Redirect
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ "@service_container" ,"%httpProtocol%://%site_domain%/"  ]

    short_url:
            class: Ibtikar\GlanceDashboardBundle\Service\ShortUrl
            arguments: [ "@doctrine_mongodb", "@redirect", "%httpProtocol%://%site_domain%/", "@service_container" ]

    app.twig.popover_factory_extension:
        class: Ibtikar\GlanceDashboardBundle\Service\PopoverFactoryExtension
        arguments: ["@translator"]
        tags:
            - { name: twig.extension }

#    translator:
#        class: Ibtikar\GlanceDashboardBundle\Translation\FallbackTranslator
#
#    app.decorating_translator:
#        class: Ibtikar\GlanceDashboardBundle\Translation\FallbackTranslator
#        decorates: translator
#        arguments: ['@app.decorating_translator.inner']
#        public:    false
    validator.international.phone:
        class: Ibtikar\GlanceDashboardBundle\Validator\InternationalPhoneValidator
        tags:
            - { name: validator.constraint_validator, alias: international-phone }

    backend.form.type.phone:
        class: Ibtikar\GlanceDashboardBundle\Form\Type\PhoneType
        tags:
            - { name: form.type, alias: phone }
        arguments: ["@service_container"]



    user_like:
        class: Ibtikar\GlanceDashboardBundle\Service\UserLike
        arguments: ["@doctrine_mongodb","@service_container"]

    user_read_later:
        class: Ibtikar\GlanceDashboardBundle\Service\UserReadLater
        arguments: ["@doctrine_mongodb"]

#
