services:
#    ibtikar_glance_dashboard.example:
#        class: Ibtikar\GlanceDashboardBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    list_view:
        class: Ibtikar\GlanceDashboardBundle\Service\ListView
        arguments: ["@service_container" ]

    base_email:
        class: Ibtikar\GlanceDashboardBundle\Service\BaseEmail
        arguments: ["@templating"]

    not_found_listener:
        class: Ibtikar\GlanceDashboardBundle\Service\NotFoundExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
        arguments: [ "@templating" ]