ibtikar_glance_dashboard_blog_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:create }

ibtikar_glance_dashboard_blog_edit:
    path:  /edit/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:edit}

ibtikar_glance_dashboard_blog_delete:
    path:  /delete/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:delete }

ibtikar_glance_dashboard_blog_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:list }

ibtikar_glance_dashboard_blog_delete:
    path: /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:delete}

ibtikar_glance_dashboard_blog_bulk_actions:
    path: /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:bulk}

ibtikar_glance_dashboard_blog_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:changeListColumns }

get_tags:
    path: /get-tags
    defaults: { _controller: IbtikarGlanceDashboardBundle:Blog:getTags }