ibtikar_glance_dashboard_competition_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Competition:create }

ibtikar_glance_dashboard_competition_new:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/competition/new.yml"
    prefix:   /competition-new

ibtikar_glance_dashboard_message_inprogress:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/competition/publish.yml"
    prefix:   /competition-publish

ibtikar_glance_dashboard_message_close:
    resource: "@IbtikarGlanceDashboardBundle/Resources/config/routes/competition/unpublish.yml"
    prefix:   /competition-unpublish

ibtikar_glance_dashboard_competitionanswer_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Competition\CompetitionAnswer:list }


ibtikar_glance_dashboard_competitionanswer_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Competition\CompetitionAnswer:changeListColumns }

