ibtikar_glance_dashboard_recipe_create:
    path:  /create
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:create }

ibtikar_glance_dashboard_recipe_edit:
    path:  /edit/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:edit}

ibtikar_glance_dashboard_recipe_delete:
    path:  /delete/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:delete }

ibtikar_glance_dashboard_recipe_list:
    path: /list
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:list }

ibtikar_glance_dashboard_recipe_delete:
    path: /delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:delete}

ibtikar_glance_dashboard_recipe_bulk_actions:
    path: /bulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:bulk}

ibtikar_glance_dashboard_recipe_check_field_unique:
    path: /checkfieldUnique
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:checkFieldUnique }

ibtikar_glance_dashboard_recipe_change_list_columns:
    path:  /change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:changeListColumns }

get_tags:
    path: /get-tags
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:getTags }

ibtikar_glance_dashboard_recipe_check_material_published:
    path: /checkMaterialPublished
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:checkMaterialPublished }

ibtikar_glance_dashboard_recipe_check_material_published_bulk:
    path: /checkMaterialPublishedBulk
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:checkMaterialPublishedBulk }

ibtikar_glance_dashboard_recipe_related_material_search:
    path:  /related-material-search/{collectionType}
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:searchRelated, collectionType ~ }

ibtikar_glance_dashboard_recipe_related_material_delete:
    path: /related-material-delete
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:relatedMaterialDelete }

ibtikar_glance_dashboard_recipe_related_material_add:
    path: /related-material-add
    defaults: { _controller: IbtikarGlanceDashboardBundle:Recipe:relatedMaterialAdd }

