ibtikar_glance_dashboard_starsrejected_list_rejected_stars:
    path:  /list-rejected-stars
    defaults: { _controller: IbtikarGlanceDashboardBundle:stars\Rejected:listRejectedStars }

ibtikar_glance_dashboard_starsrejected_approve:
    path:  /approve/{id}
    defaults: { _controller: IbtikarGlanceDashboardBundle:stars\Rejected:approve }

ibtikar_glance_dashboard_starsrejected_list_rejected_stars_change_list_columns:
    path:  /rejected-stars-change-list-columns
    defaults: { _controller: IbtikarGlanceDashboardBundle:stars\Rejected:changeListRejectedStarsColumns }
