<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineRepository extends DocumentRepository
{

      public function getHomeMagazine()
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Magazine')
                ->field('status')->equals('publish')
                ->field('publishLocations.section')->equals('home-magazine')
                ->field('coverPhoto')->prime(true)
                ->sort('publishedAt', 'DESC')
                ->getQuery()->execute();
    }
}
