<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends DocumentRepository {

    public function getRecipeMedia($recipeId)
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Media')
                ->field('deleted')->equals(FALSE)
                ->field('recipe')->equals($recipeId)
                ->sort('order', 'ASC')
                ->getQuery()->execute();
    }

    public function getproductsMedia($ids)
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Media')
                ->field('deleted')->equals(FALSE)
                ->field('products')->in($ids)
                ->sort('order', 'ASC')
                ->getQuery()->execute();
    }

    public function getContactMessagesMedia($ids) {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Media')
                        ->field('deleted')->equals(FALSE)
                        ->field('contactMessage')->in($ids)
                        ->sort('order', 'ASC')
                        ->getQuery()->execute();
    }

    public function getSeasonMedia($id) {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Media')
                        ->field('deleted')->equals(FALSE)
                        ->field('season')->equals($id)
                        ->sort('order', 'ASC')
                        ->getQuery()->execute();
    }
}
