<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends DocumentRepository {

    public function getRecipeMedia($recipeId)
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Media')
                ->field('deleted')->equals(FALSE)
                ->field('recipe')->equals($recipeId)
                ->sort('order', 'ASC')
                ->getQuery()->execute();
    }
}
