<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends DocumentRepository
{


    public function getPublishedproduct($skip = 0, $limit = 10)
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Product')
                ->field('deleted')->equals(FALSE)
                ->field('coverPhoto')->prime(true)
                ->sort('createdAt', 'DESC')
                ->eagerCursor()
                ->limit($limit)
                ->skip($skip)
                ->getQuery()->execute();
    }
}
