<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends DocumentRepository
{

    public function getDailySolution()
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Recipe')
                ->field('status')->equals(Recipe::$statuses['publish'])
                ->field('publishLocations.section')->equals('Daily-solution')
                ->sort('publishedAt', 'DESC')
                ->getQuery()->getSingleResult();
    }

    public function getPreviousDailySolution($skip = 0, $limit = 4)
    {
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Recipe')
                ->field('status')->equals(Recipe::$statuses['publish'])
                ->field('publishLocations.section')->notEqual('Daily-solution')
                ->field('deleted')->equals(FALSE)
                ->field('coverPhoto')->prime(true)
                ->sort('publishedAt', 'DESC')
                ->eagerCursor()
                ->limit($limit)
                ->skip($skip)
                ->getQuery()->execute();
    }

    public function getMostView($skip = 0, $limit = 4)
    {
        $date = new \DateTime();
        $date->modify("-1 month");
        return $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Recipe')
                ->field('status')->equals(Recipe::$statuses['publish'])
                ->field('deleted')->equals(FALSE)
                ->field('publishedAt')->gte($date)
                ->sort('noOfViews', 'DESC')
                ->eagerCursor()
                ->limit($limit)
                ->skip($skip)
                ->getQuery()->execute();
    }
}
