<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SlugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlugRepository extends DocumentRepository {

    /**
     * @author Ahmad Gamal <a.gamal@ibtikar.net.sa>
     * @param string $shortCode
     * @return object
     */
    function getDocumentBySlug($shortCode) {
        $queryBuilder =  $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:Slug')
                                  ->field('deleted')->equals(FALSE);

        $queryBuilder->addOr($queryBuilder->expr()->field('slugAr')->equals($shortCode));
        $queryBuilder->addOr($queryBuilder->expr()->field('slugEn')->equals($shortCode));

        return $queryBuilder->getQuery()->count();
    }

}
