<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserDocumentReadLaterRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserDocumentReadLaterRepository extends DocumentRepository
{

    public function getUserDocumentReadLater($documentId, $userId)
    {
        return $this->findOneBy(array('document.$id' => new \MongoId($documentId), 'user.$id' => new \MongoId($userId)));
    }

    public function getDocumentReadLater($documentId)
    {
        return $this->findBy(array('document.$id' => new \MongoId($documentId)));
    }

    public function getUserDocumentReadLaterList($userId, $limit, $skip = 0, $filter = null)
    {
        $documents = $this->dm->createQueryBuilder('IbtikarGlanceDashboardBundle:UserDocumentReadLater')
                ->field('user.$id')->equals(new \MongoId($userId));
        if ($filter != null && $filter != '') {
            $documents->field('documentType')->equals($filter);
        }
        $documents->sort(array('createdAt' => 'DESC'));
        if ($limit != 0) {
            $documents->limit($limit);
        }
        $documents->skip($skip);
        return $documents->getQuery()->execute();
    }
}
