<?php

namespace Ibtikar\GlanceDashboardBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserDocumentLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDocumentLikeRepository extends DocumentRepository {

    /**
     * @author Mahmoud Mostafa <mahmoud.mostafa@ibtikar.net.sa>
     * @param string $documentId
     * @param string $userId
     * @return DocumentlLike
     */
    public function getUserDocumentLike($documentId, $userId) {
        return $this->findOneBy(array('document.$id' => new \MongoId($documentId), 'user.$id' => new \MongoId($userId)));
    }

    public function getDocumentLike($documentId) {
        return $this->findBy(array('document.$id' => new \MongoId($documentId),'deleted'=>FALSE));
    }

}
